/**
 * Semantic Cluster Definitions for K-Means (K=15)
 * Generated by Phase 1 ML Model & Seeded into Supabase
 */
export const CLUSTERS = [
  { id: 0, name: 'Contemporary Romance', fullName: 'Contemporary Romance & Modern Relationships', desc: 'Emotional fiction, love stories & modern relationships', badge: 'Cluster 0' },
  { id: 1, name: 'Historical & Literary Prose', fullName: 'Historical Fiction & Literary Period Sagas', desc: 'War chronicles, historical memoirs & award-winning prose', badge: 'Cluster 1' },
  { id: 2, name: 'Mystery & Crime Fiction', fullName: 'Mystery, Detective & Crime Investigations', desc: 'Whodunits, police procedurals, detective stories & noir', badge: 'Cluster 2' },
  { id: 3, name: 'Non-Fiction & Memoirs', fullName: 'Non-Fiction, Memoirs & Autobiographies', desc: 'True stories, biographies, cultural essays & memoirs', badge: 'Cluster 3' },
  { id: 4, name: 'Dystopian & Thrillers', fullName: 'Dystopian, Sci-Fi & Psychological Thrillers', desc: 'Suspense, post-apocalyptic survivals & investigative mysteries', badge: 'Cluster 4' },
  { id: 5, name: 'Classics & Philosophy', fullName: 'Classic Literature & Philosophical Prose', desc: 'Enduring philosophical essays, heritage classics & thought', badge: 'Cluster 5' },
  { id: 6, name: 'Science Fiction & Future', fullName: 'Science Fiction & Speculative Futures', desc: 'Space exploration, artificial intelligence & speculative worlds', badge: 'Cluster 6' },
  { id: 7, name: "Children's & Illustrated", fullName: "Children's Literature & Illustrated Tales", desc: 'Bedtime stories, classic fairy tales & juvenile adventures', badge: 'Cluster 7' },
  { id: 8, name: 'Poetry & Drama', fullName: 'Poetry, Dramatic Plays & Anthologies', desc: 'Verse, theatrical scripts & curated literary anthologies', badge: 'Cluster 8' },
  { id: 9, name: 'Horror & Dark Fantasy', fullName: 'Gothic Horror, Supernatural & Dark Lore', desc: 'Dark suspense, vampire lore, haunted tales & psychological terror', badge: 'Cluster 9' },
  { id: 10, name: 'Magic & Young Adult', fullName: 'Magic, Sorcery & YA Coming-of-Age', desc: 'Coming-of-age journeys, sorcery & academy adventures', badge: 'Cluster 10' },
  { id: 11, name: 'Action & Adventure Sagas', fullName: 'Action, Survival & Epic Adventures', desc: 'High-seas expeditions, martial action & heroic escapades', badge: 'Cluster 11' },
  { id: 12, name: 'Humor & Satire', fullName: 'Humor, Satirical Essays & Comedy', desc: 'Witty commentaries, humorous tales & comedic fiction', badge: 'Cluster 12' },
  { id: 13, name: 'Paranormal & Urban Fantasy', fullName: 'Paranormal Romance & Urban Supernatural', desc: 'Mythical beings, urban supernatural & romantic fantasy', badge: 'Cluster 13' },
  { id: 14, name: 'Epic & Classical Fantasy', fullName: 'Epic & Classical High Fantasy Sagas', desc: 'High fantasy realms, ancient sagas & mythic lore', badge: 'Cluster 14' },
];

export const getClusterById = (id) => {
  const numericId = Number(id);
  return CLUSTERS.find((c) => c.id === numericId) || {
    id: numericId,
    name: `Cluster ${numericId}`,
    fullName: `Semantic Cluster ${numericId}`,
    desc: 'Thematic cluster partitioned by K-Means algorithm',
    badge: `Cluster ${numericId}`
  };
};
